apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: 339712715508.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
      env:
        - name: DBHOST
          value: mysql-service
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: admin
        - name: DBPWD
          value: admin123
        - name: DATABASE
          value: employees
      ports:
        - containerPort: 8080
